# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08d3ae3dc75cfc522908dca02649d70165a8a1edfe694a57239effb35149c124ce3d19da0bd4832db2aa6cd6c2b9a65350722140a8d6ecb4338160f239afde2

test:
  secret_key_base: 8d054121d61b2762789bfc49879e78bf51074ca1d7881941aeb4cd501db662aae6b65e073a2d07aa458c547d75fce945f6a8c0e84743d4f4426ad75b0325af6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
